spring:
  data:
    elasticsearch:
      # 集群名
      cluster-name: commerce
      # 连接节点,注意在集群中通信都是9300端口，否则会报错无法连接上！
      cluster-nodes: localhost:9300
      repositories:
        # 仓库中数据存储
        enabled: true
